"""[D0] Positive-anchor coverage per Train GT box (starvation gate; GPU or CPU-torch).

Before retraining, quantify the starvation hypothesis DIRECTLY (P2-UPDATE B2 loosened the
matcher on a hypothesis; this measures it). For every Train union GT box, count how many
anchors clear ``fg_iou_thresh`` against it — the positives the classification head actually
sees (excluding the single anchor ``allow_low_quality_matches`` force-assigns). Anchors are
generated by the SAME ``build_retinanet`` config that trains, on each volume's iso frame,
and GT boxes are resized by the SAME ``model.transform`` so anchor/box frames agree.

GATE READ (record in RESULTS [D0]):
  - mode >= 3 positives/GT across all size bins -> coverage adequate; ranking failure is
    convergence/recipe (D1-D5); D6/ATSS NOT needed.
  - mode <= 1 (esp. small-diag bins) -> genuine starvation the fixed matcher only papers
    over via the 1 forced low-quality positive; D6/ATSS fires in Stage 2.

Usage (server):
    python scripts/phase2_anchor_coverage.py --device cuda
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np

from abus_jcr import cache as K
from abus_jcr import conventions as C
from abus_jcr.detect.slice_det_dataset import boxes_halfopen_for
from _phase2_common import add_phase2_paths, assert_device, cache_root, load_manifest, load_slice_boxes

DIAG_BINS = [(0, 16), (16, 32), (32, 64), (64, 128), (128, np.inf)]


def _bin_label(diag: float) -> str:
    for lo, hi in DIAG_BINS:
        if lo <= diag < hi:
            return f"[{lo},{hi if np.isfinite(hi) else 'inf'})"
    return "[128,inf)"


def _iou_box_vs_anchors(box, anchors):
    """IoU of one (4,) box vs (A,4) anchors — both (x1,y1,x2,y2)."""
    x1 = np.maximum(box[0], anchors[:, 0]); y1 = np.maximum(box[1], anchors[:, 1])
    x2 = np.minimum(box[2], anchors[:, 2]); y2 = np.minimum(box[3], anchors[:, 3])
    iw = np.clip(x2 - x1, 0, None); ih = np.clip(y2 - y1, 0, None)
    inter = iw * ih
    ab = (box[2] - box[0]) * (box[3] - box[1])
    aa = (anchors[:, 2] - anchors[:, 0]) * (anchors[:, 3] - anchors[:, 1])
    union = ab + aa - inter
    return np.where(union > 0, inter / union, 0.0)


def main() -> int:
    parser = argparse.ArgumentParser(description="[D0] positive-anchor coverage per Train GT box")
    add_phase2_paths(parser)
    parser.add_argument("--device", default="cuda")
    args = parser.parse_args()

    assert_device(args.device)
    import torch
    from abus_jcr.detect.retinanet import build_retinanet

    manifest = load_manifest(args)
    croot = cache_root(args)
    sb_train = load_slice_boxes(args, "Train")
    train_ids = sorted(int(v) for v in manifest[manifest["split"] == "train"]["volume_id"])

    # Weights are irrelevant to anchor geometry; build once, eval mode.
    model = build_retinanet(c_channels=C.C_CHANNELS, num_classes=C.DET_NUM_CLASSES, pretrained=False)
    model.to(args.device).eval()
    fg = float(model.proposal_matcher.high_threshold)  # == DET_FG_IOU_THRESH

    counts, diags, bins = [], [], []
    with torch.no_grad():
        for vid in train_ids:
            vb = sb_train[sb_train["volume_id"] == vid]
            zs = sorted(int(z) for z in vb["slice_z"].unique())
            if not zs:
                continue
            meta = K.read_meta(croot, vid)
            d0, d1 = int(meta["iso_shape"][C.IN_PLANE_ROW_AXIS]), int(meta["iso_shape"][C.IN_PLANE_COL_AXIS])
            # gather all this volume's GT boxes (original iso frame) for one transform pass
            boxes_orig = np.concatenate(
                [boxes_halfopen_for(sb_train, vid, z) for z in zs], axis=0)
            if len(boxes_orig) == 0:
                continue
            dummy = torch.zeros((C.C_CHANNELS, d0, d1), dtype=torch.float32, device=args.device)
            tgt = [{"boxes": torch.as_tensor(boxes_orig, dtype=torch.float32, device=args.device),
                    "labels": torch.ones(len(boxes_orig), dtype=torch.int64, device=args.device)}]
            image_list, targets = model.transform([dummy], tgt)
            feats = model.backbone(image_list.tensors)
            feat_list = list(feats.values())
            anchors = model.anchor_generator(image_list, feat_list)[0].cpu().numpy()  # (A,4)
            boxes_resized = targets[0]["boxes"].cpu().numpy()
            for bo, br in zip(boxes_orig, boxes_resized):
                ious = _iou_box_vs_anchors(br, anchors)
                counts.append(int((ious >= fg).sum()))
                diag = float(np.hypot(bo[2] - bo[0], bo[3] - bo[1]))  # original-frame diag (iso px)
                diags.append(diag); bins.append(_bin_label(diag))

    counts = np.asarray(counts); diags = np.asarray(diags); bins = np.asarray(bins)
    n = len(counts)
    print(f"# [D0] positive-anchor coverage (fg_iou_thresh={fg}, n_gt_boxes={n}, "
          f"n_train_vols={len(train_ids)})\n")

    def stats(c):
        c = np.asarray(c)
        if len(c) == 0:
            return {}
        mode = int(np.bincount(c).argmax())
        return {"n": int(len(c)), "frac_zero": float((c == 0).mean()), "mode": mode,
                "p1": int(np.percentile(c, 1)), "median": float(np.median(c)),
                "p90": float(np.percentile(c, 90)), "mean": float(c.mean())}

    overall = stats(counts)
    print(f"OVERALL: n={overall['n']}  frac_zero={overall['frac_zero']:.3f}  mode={overall['mode']}  "
          f"p1={overall['p1']}  median={overall['median']}  p90={overall['p90']}  mean={overall['mean']:.2f}\n")
    print(f"{'diag bin':>14} {'n':>6} {'frac0':>7} {'mode':>5} {'median':>7} {'p90':>6}")
    per_bin = {}
    for lo, hi in DIAG_BINS:
        lab = f"[{lo},{hi if np.isfinite(hi) else 'inf'})"
        s = stats(counts[bins == lab])
        per_bin[lab] = s
        if s:
            print(f"{lab:>14} {s['n']:>6} {s['frac_zero']:>7.3f} {s['mode']:>5} "
                  f"{s['median']:>7.1f} {s['p90']:>6.1f}")

    small_modes = [per_bin[b]["mode"] for b in per_bin if per_bin[b] and b in ("[0,16)", "[16,32)")]
    verdict = ("COVERAGE ADEQUATE (mode>=3 in all bins) -> D6/ATSS NOT needed; ranking failure is D1-D5"
               if overall["mode"] >= 3 and all(m >= 3 for m in small_modes)
               else "STARVATION (mode<=1 in a small-diag bin or overall) -> D6/ATSS fires in Stage 2")
    print(f"\nVERDICT: {verdict}")

    out_dir = Path(args.out_root) / "stats"
    out_dir.mkdir(parents=True, exist_ok=True)
    payload = {"fg_iou_thresh": fg, "overall": overall, "per_bin": per_bin, "verdict": verdict}
    (out_dir / "anchor_coverage.json").write_text(json.dumps(payload, indent=2))
    print(f"json = {out_dir / 'anchor_coverage.json'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
